discourse-review-plugin:
  review_form_enabled:
    default: false
    client: true
  review_form_email:
    default: "review@example.com"
    client: true
  review_form_intro:
    default: "Please leave a review!"
    client: true
